create table shelter_assignment (
    id bigint generated by DEFAULT as identity(start with 1) not null primary key,
    shelter_id bigint not null foreign key references shelter (id),
    team_id bigint not null foreign key references team (id)
);