create table car (
    id bigint generated by DEFAULT as identity(start with 1) not null primary key,
    name varchar(255) not null
);

create table car_teams (
    id bigint generated by DEFAULT as identity(start with 1) not null primary key,
    car_id bigint not null foreign key references car (id),
    team_id bigint not null foreign key references team (id)
)