create sequence HIBERNATE_SEQUENCE as INTEGER start with 1000 increment by 1;

create table team (
    id bigint generated by DEFAULT as identity(start with 1) not null primary key,
    name varchar(255) not null
);