create table shelter (
    id bigint generated by DEFAULT as identity(start with 1) not null primary key,
    name varchar(255) not null,
    street varchar(255) not null,
    zip varchar(50) not null,
    city varchar(50) not null,
    country varchar(50) not null
);